// // typeof 6 - Mostra o tipo de valor
// console.log(typeof 6)
// var nome = window.prompt("Qual o  seu nome ?")
// window.alert("É um  grande prazer "+ nome)
// // console.log(nome)
 var num1 = Number(window.prompt("D: "))
 console.log(num1/3)
 var stri = String(num1/3)
 window.alert("A string é "+ stri)
 document.writeln("SFDg")